# Generated by Django 5.1.7 on 2025-03-07 15:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fyter', '0002_client_formateur_freelancer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='ClientUser',
        ),
    ]
