# Generated by Django 5.1.7 on 2025-03-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fyter', '0004_remove_clientuser_phone_number_clientuser_industry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='beginner', help_text="Freelancer's skill level", max_length=20),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Hourly rate of the freelancer', max_digits=3),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Rating score (0 to 10)', max_digits=3),
        ),
    ]
