# Generated by Django 5.1.7 on 2025-03-08 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fyter', '0005_freelancer_level_freelancer_rate_freelancer_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=2.0, help_text='Hourly rate of the freelancer', max_digits=3),
        ),
    ]
