# Generated by Django 5.1.7 on 2025-03-12 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fyter', '0007_project_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='state',
            field=models.CharField(blank=True, default='free', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='open', max_length=50),
        ),
    ]
