# Generated by Django 5.1.7 on 2025-03-12 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fyter', '0008_freelancer_state_alter_project_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostuledRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postuled_projects', to='Fyter.freelancer')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postuled_requests', to='Fyter.project')),
            ],
            options={
                'unique_together': {('project', 'freelancer')},
            },
        ),
    ]
