# Generated by Django 5.1.7 on 2025-03-25 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fyter', '0011_privetchat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chatrooms', to='Fyter.project'),
            preserve_default=False,
        ),
    ]
