# Generated by Django 5.2 on 2025-05-17 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fyter', '0013_postuledrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('sample_image', models.ImageField(blank=True, null=True, upload_to='format_samples/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('availability', models.BooleanField(default=True)),
                ('category', models.CharField(max_length=100)),
                ('estimated_delivery_time', models.PositiveIntegerField(default=1, help_text='Estimated delivery time in days')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('featured', 'Featured')], default='active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormatOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirements', models.TextField(help_text="Client's specific requirements for this format")),
                ('attachments', models.FileField(blank=True, null=True, upload_to='format_order_attachments/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('review', 'Under Review'), ('revision', 'Needs Revision'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text="Client's rating (1-5)", null=True)),
                ('review', models.TextField(blank=True, help_text="Client's review", null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='format_orders', to=settings.AUTH_USER_MODEL)),
                ('format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='Fyter.format')),
            ],
        ),
        migrations.CreateModel(
            name='FormatDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='format_deliveries/')),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='Fyter.formatorder')),
            ],
        ),
        migrations.CreateModel(
            name='Formatter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(help_text="Formatter's area of specialization", max_length=255)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('skills', models.TextField(blank=True, help_text='List of formatting skills')),
                ('verified', models.BooleanField(default=False)),
                ('bio', models.TextField(blank=True, null=True)),
                ('formats_completed', models.PositiveIntegerField(default=0, help_text='Number of completed formats')),
                ('rate', models.DecimalField(decimal_places=2, default=2.0, help_text='Hourly rate of the formatter', max_digits=3)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='beginner', help_text="Formatter's skill level", max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='formatter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='format',
            name='formatter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formats', to='Fyter.formatter'),
        ),
    ]
