# Generated by Django 5.1.7 on 2025-05-23 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fyter', '0014_format_formatorder_formatdelivery_formatter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formatorder',
            name='format',
        ),
        migrations.RemoveField(
            model_name='formatdelivery',
            name='order',
        ),
        migrations.RemoveField(
            model_name='formatorder',
            name='client',
        ),
        migrations.RemoveField(
            model_name='formatter',
            name='user',
        ),
        migrations.DeleteModel(
            name='Format',
        ),
        migrations.DeleteModel(
            name='FormatDelivery',
        ),
        migrations.DeleteModel(
            name='FormatOrder',
        ),
        migrations.DeleteModel(
            name='Formatter',
        ),
    ]
