# Generated by Django 5.1.7 on 2025-05-25 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fyter', '0015_remove_formatorder_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='privetchat',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
