# Generated by Django 5.1.7 on 2025-06-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fyter', '0016_privetchat_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('normal', 'Normal'), ('soloFin', 'SoloFin'), ('bettaArena', 'BettaArena')], default='normal', max_length=50),
        ),
    ]
