# Generated by Django 5.1.7 on 2025-06-03 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fyter', '0017_remove_project_status_project_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='open', max_length=50),
        ),
    ]
