# Generated by Django 5.1.7 on 2025-06-18 09:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fyter', '0019_alter_postuledrequest_status_solofinrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='phase',
            field=models.CharField(choices=[('phase1', 'Phase 1'), ('phase2', 'Phase 2'), ('phase3', 'Phase 3'), ('phase4', 'Phase 4')], default='phase1', max_length=50),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='users_banned',
            field=models.ManyToManyField(blank=True, related_name='banned_chatrooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
