# Generated by Django 5.1.7 on 2025-06-21 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fyter', '0020_chatroom_phase_chatroom_users_banned'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chatrooms', to='Fyter.service'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chatrooms', to='Fyter.project'),
        ),
    ]
