# Generated by Django 5.2 on 2025-05-17 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_first_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('freelancer', 'Freelancer'), ('formateur', 'Formateur'), ('formatter', 'Formatter'), ('admin', 'Admin')], default='client', max_length=20),
        ),
    ]
