# Generated by Django 5.1.7 on 2025-05-23 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('freelancer', 'Freelancer'), ('formateur', 'Formateur'), ('admin', 'Admin')], default='client', max_length=20),
        ),
    ]
